# 出力精度の制御

In [1]:
import numpy as np
from pprint import pprint
import scipy.linalg as linalg

np.set_printoptions(precision=3, suppress=True)

a = np.array([[2,5], [4,1]])
l,P = np.linalg.eig(a)
pprint(l)
pprint(P)

array([ 6., -3.])
array([[ 0.781, -0.707],
       [ 0.625,  0.707]])


# 行列，ベクトルの生成

In [2]:
import numpy as np
import scipy as sp
list_a = [1,2]
list_b = [3,4]
np_a = np.array([list_a, list_b])
print(np_a)

sp_a = sp.array([list_a, list_b])
print(sp_a)

np_m = np.matrix([list_a, list_b])
print(np_m)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [22]:
list_a = [1,2]

np_a_1 = np.array(list_a)
print(np_a_1)

np_v = np.array([list_a])
print(np_v)
# np.vectorはない．

[1 2]
[[1 2]]


## ゼロ行列，単位行列

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 転置(transpose)

In [26]:
print(np_a.transpose())
print(sp_a.transpose())
print(np_m.transpose())

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [27]:
np_v.transpose()

array([[1],
       [2]])

# 行列，ベクトルの演算

## ドット積

In [28]:
np.dot(np_a,np.transpose(np_v))

array([[ 5],
       [11]])

In [29]:
np_v.dot(np_a)

array([[ 7, 10]])

In [30]:
np_v.dot(np_v.transpose())

array([[5]])

## 外積，outer, cross¶

In [31]:
v1 = np.array([1,1,3])
v2 = np.array([1,2,-1])

In [32]:
np.outer(v1,v2)

array([[ 1,  2, -1],
       [ 1,  2, -1],
       [ 3,  6, -3]])

In [33]:
np.cross(v1,v2)

array([-7,  4,  1])

## スカラー三重積

In [34]:
v3 = np.array([-1,2,1])
np.dot(np.cross(v1,v2),v3)

16

# 行列要素のとりだし，追加

In [35]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
# i行j列の要素の取り出し
a[1,1]

5

In [36]:
a[:2,1:4]

array([[2, 3],
       [5, 6]])

In [37]:
col_0 = a[:,0]
print(col_0)

[1 4 7]


In [38]:
row_1 = a[1,:]
print(row_1)

[4 5 6]


In [39]:
b = np.array([1,2,3])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [40]:
np.column_stack((a,b))

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

# 掃き出し, LU分解

In [44]:
import scipy.linalg

a = np.array([[1,-1,-1],[1,-1,1],[1,1,-1]]) # 教材にこの行はなかったが、結果から逆算するとこの代入が必要

P, L, U = scipy.linalg.lu(a)

print(P)
print(L)
print(U)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 0. 1.]]
[[ 1. -1. -1.]
 [ 0.  2.  0.]
 [ 0.  0.  2.]]


In [45]:
b = np.array([1,-1,-1]) # 教材にこの行はなかったが、結果から逆算するとこの代入が必要
ab = np.column_stack((a,b))
P, L, U = scipy.linalg.lu(ab)
print(P)
print(L)
print(U)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 0. 1.]]
[[ 1. -1. -1.  1.]
 [ 0.  2.  0. -2.]
 [ 0.  0.  2. -2.]]


## 階数

In [46]:
print(a)

print(np.linalg.matrix_rank(a))
print(np.rank(a)) #deprecatedなんでやめろって，
# 関数名とかlibの区分けに統一性がないよね．．．


[[ 1 -1 -1]
 [ 1 -1  1]
 [ 1  1 -1]]
3
2


/Users/syasin/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  after removing the cwd from sys.path.


# 逆行列

In [47]:
a = np.array([[1,2],[3,4]])
scipy.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# 行列式

In [48]:
c = np.array([[1,1],[1,2]])
print(np.linalg.det(c))

a = np.array([[1,2],[3,4]])
scipy.linalg.det(a)

1.0


-2.0

# 連立方程式の解

$$
x - y -z = 1\\
x - y +z = -1\\
x + y -z = -1
$$

In [49]:
a=np.array([[1,-1,-1],[1,-1,1],[1,1,-1]])
b = np.array([1,-1,-1])
scipy.linalg.inv(a).dot(b)

array([-1., -1., -1.])

$$
\left\{
    \begin {array}{cl}
    x+y+z&=0\\
    ax+by+cz&=0\\
    bcx+cay+abz&=(a-b)(b-c)(c-a)
    \end {array} \right.
$$

In [50]:
from pprint import pprint
from sympy import *
a,b,c,x,y,z = symbols('a b c x y z')

A = Matrix([[1,1,1],[a,b,c],[b*c,c*a,a*b]])
bb = Matrix([0,0,(a-b)*(b-c)*(c-a)])
print(A)
print(bb)
Ainv = A.inv()
res = Ainv * bb
pprint(simplify(res[0]))
pprint(simplify(res[1]))
pprint(simplify(res[2]))

Matrix([[1, 1, 1], [a, b, c], [b*c, a*c, a*b]])
Matrix([[0], [0], [(-a + c)*(a - b)*(b - c)]])
-b + c
a - c
-a + b


# 固有値，固有ベクトル

In [51]:
a = np.array([[1,1],[0,2]])
l, P = scipy.linalg.eig(a)
print(l)
print(P)

[1.+0.j 2.+0.j]
[[1.    0.707]
 [0.    0.707]]


## ベクトルの規格化

In [52]:
# eigの固有ベクトルは規格化されている
p_norm = np.linalg.norm(P[:,1])
print(p_norm)

0.9999999999999999


# 対角化

In [53]:
np.dot(np.dot(np.linalg.inv(P),a),P)
#np.dot(np.dot(np.linalg.inv(P),a),P)

array([[1., 0.],
       [0., 2.]])

## 課題
行列
$$
A\, := \, \left[
\begin {array}{ccc} 
2&0&1\\
0&3&0\\
1&0&2
\end {array} \right]
$$

を対角化する変換行列$P$を求め，対角化せよ．

In [58]:
import numpy as np

A = np.array([[2,0,1],[0,3,0],[1,0,2]])
l, P = np.linalg.eig(A)
print(l)
print(P)

np.dot(np.dot(np.linalg.inv(P),A),P)

[3. 1. 3.]
[[ 0.707 -0.707  0.   ]
 [ 0.     0.     1.   ]
 [ 0.707  0.707  0.   ]]


array([[3., 0., 0.],
       [0., 1., 0.],
       [0., 0., 3.]])

In [57]:
import numpy as np
from math import pi

np.linspace(0,2*pi,9)

array([0.   , 0.785, 1.571, 2.356, 3.142, 3.927, 4.712, 5.498, 6.283])